language: groovy
jdk:
- openjdk7
script: "./travis-build.sh"
env:
  global:
  - TERM=dumb
  - GRADLE_OPTS="-Xmx768m -Xms256m -XX:MaxPermSize=256m -XX:+CMSClassUnloadingEnabled"
  - secure: CFwWLeLqRIZr4IQXJppe/OYojYTtuddrtz6ZEzCkQwcL/oGPJPomK0Sg4auAS4MrYQN+W8idBWyDvje+HOtwC6ApKjpKqFwfDZbYAbUYnGsZ+ucR+pCjh47ymIgPCjj21jYA1j/azbVu18OsWvq8kw75yLGW9WspNeu4JbPwHh0=
